FRW-10984 Ignore warnings

diff --git a/.github/workflows/non-releasable-branches.yml b/.github/workflows/non-releasable-branches.yml
--- a/.github/workflows/non-releasable-branches.yml
+++ b/.github/workflows/non-releasable-branches.yml
@@ -39,8 +39,8 @@ jobs:
 
             - name: Run format check (Errors only)
               run: |
-                  OUTPUT=$(npm run format:check -- --base=origin/next --log-level=error  2>&1 || true)
-                  if echo "$OUTPUT" | grep -q 'error' && echo "$OUTPUT" | grep -vq 'warn'; then
+                  OUTPUT=$(npm run format:check -- --base=origin/next  2>&1 || true)
+                  if echo "$OUTPUT" | grep -q 'error'; then
                       echo "::error::Prettier found formatting errors"
                       echo "$OUTPUT"
                       exit 1
